<?php

namespace ContainerJTZZlzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_75CNgOIService extends App_Shared_Infrastructure_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.75CNgOI' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Application/Command/CommandHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Application/Command/ConfirmSpecialistSkill/ConfirmSpecialistSkillCommandHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Domain/Service/SkillConfirmationService.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Domain/Repository/SpecialistRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Infrastructure/Repository/SpecialistRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Domain/Repository/SkillRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Infrastructure/Repository/SkillRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Domain/Factory/SkillConfirmationFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Domain/Repository/SkillConfirmationRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Infrastructure/Repository/SkillConfirmationRepository.php';

        return $container->privates['.messenger.handler_descriptor.75CNgOI'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Skills\Application\Command\ConfirmSpecialistSkill\ConfirmSpecialistSkillCommandHandler(new \App\Skills\Domain\Service\SkillConfirmationService(new \App\Skills\Infrastructure\Repository\SpecialistRepository(), new \App\Skills\Infrastructure\Repository\SkillRepository(), new \App\Skills\Domain\Factory\SkillConfirmationFactory(), new \App\Skills\Infrastructure\Repository\SkillConfirmationRepository())), []);
    }
}
