<?php

namespace ContainerJTZZlzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_4yNdbVHService extends App_Shared_Infrastructure_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.4yNdbVH' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Application/Command/CommandHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Users/Application/Command/CreateUser/CreateUserCommandHandler.php';

        return $container->privates['.messenger.handler_descriptor.4yNdbVH'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Users\Application\Command\CreateUser\CreateUserCommandHandler(($container->privates['App\\Users\\Infrastructure\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Users\\Domain\\Factory\\UserFactory'] ?? $container->load('getUserFactoryService'))), []);
    }
}
