<?php

namespace ContainerJTZZlzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUser_LazyService extends App_Shared_Infrastructure_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Users\Infrastructure\Console\CreateUser.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Users\\Infrastructure\\Console\\CreateUser.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:users:create-user', [], 'create user', false, function () use ($container): \App\Users\Infrastructure\Console\CreateUser {
            return ($container->privates['App\\Users\\Infrastructure\\Console\\CreateUser'] ?? $container->load('getCreateUserService'));
        });
    }
}
