<?php

namespace ContainerJTZZlzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_MessengerDebugService extends App_Shared_Infrastructure_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.messenger_debug' shared service.
     *
     * @return \Symfony\Component\Messenger\Command\DebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Command/DebugCommand.php';

        $container->privates['console.command.messenger_debug'] = $instance = new \Symfony\Component\Messenger\Command\DebugCommand(['command.bus' => ['App\\Skills\\Application\\Command\\ConfirmSpecialistSkill\\ConfirmSpecialistSkillCommand' => [0 => [0 => 'App\\Skills\\Application\\Command\\ConfirmSpecialistSkill\\ConfirmSpecialistSkillCommandHandler', 1 => []]], 'App\\Users\\Application\\Command\\CreateUser\\CreateUserCommand' => [0 => [0 => 'App\\Users\\Application\\Command\\CreateUser\\CreateUserCommandHandler', 1 => []]]], 'query.bus' => ['App\\Testing\\Application\\Query\\FindTestingSession\\FindTestingSessionQuery' => [0 => [0 => 'App\\Testing\\Application\\Query\\FindTestingSession\\FindTestingSessionQueryHandler', 1 => []]], 'App\\Users\\Application\\Query\\FindUserByEmail\\FindUserByEmailQuery' => [0 => [0 => 'App\\Users\\Application\\Query\\FindUserByEmail\\FindUserByEmailQueryHandler', 1 => []]]], 'event.bus' => ['App\\Testing\\Domain\\Event\\TestingSessionCompletedEvent' => [0 => [0 => 'App\\Testing\\Infrastructure\\EventHandler\\TestingSessionCompletedEventHandler', 1 => []]]]]);

        $instance->setName('debug:messenger');
        $instance->setDescription('List messages you can dispatch using the message buses');

        return $instance;
    }
}
