<?php

namespace ContainerJTZZlzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUserService extends App_Shared_Infrastructure_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Users\Infrastructure\Console\CreateUser' shared autowired service.
     *
     * @return \App\Users\Infrastructure\Console\CreateUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Users/Infrastructure/Console/CreateUser.php';

        $container->privates['App\\Users\\Infrastructure\\Console\\CreateUser'] = $instance = new \App\Users\Infrastructure\Console\CreateUser(($container->privates['App\\Users\\Infrastructure\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Users\\Domain\\Factory\\UserFactory'] ?? $container->load('getUserFactoryService')));

        $instance->setName('app:users:create-user');
        $instance->setDescription('create user');

        return $instance;
    }
}
