<?php

namespace ContainerJTZZlzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainEventSubscriberService extends App_Shared_Infrastructure_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Shared\Infrastructure\Doctrine\DomainEventSubscriber' shared autowired service.
     *
     * @return \App\Shared\Infrastructure\Doctrine\DomainEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Doctrine/DomainEventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Application/Event/EventBusInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/HandleTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Bus/EventBus.php';

        return $container->privates['App\\Shared\\Infrastructure\\Doctrine\\DomainEventSubscriber'] = new \App\Shared\Infrastructure\Doctrine\DomainEventSubscriber(new \App\Shared\Infrastructure\Bus\EventBus(($container->privates['query.bus'] ?? $container->load('getQuery_BusService'))), $container);
    }
}
