<?php

namespace ContainerJTZZlzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkillGroupRepositoryService extends App_Shared_Infrastructure_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Skills\Infrastructure\Repository\SkillGroupRepository' shared autowired service.
     *
     * @return \App\Skills\Infrastructure\Repository\SkillGroupRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Domain/Repository/SkillGroupRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Skills/Infrastructure/Repository/SkillGroupRepository.php';

        return $container->privates['App\\Skills\\Infrastructure\\Repository\\SkillGroupRepository'] = new \App\Skills\Infrastructure\Repository\SkillGroupRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
