<?php

namespace ContainerJTZZlzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserFactoryService extends App_Shared_Infrastructure_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Users\Domain\Factory\UserFactory' shared autowired service.
     *
     * @return \App\Users\Domain\Factory\UserFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Users/Domain/Factory/UserFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Users/Domain/Service/UserPasswordHasherInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Users/Infrastructure/UserPasswordHasher.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/password-hasher/Hasher/UserPasswordHasherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/password-hasher/Hasher/UserPasswordHasher.php';

        return $container->privates['App\\Users\\Domain\\Factory\\UserFactory'] = new \App\Users\Domain\Factory\UserFactory(new \App\Users\Infrastructure\UserPasswordHasher(new \Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher(($container->privates['security.password_hasher_factory'] ?? $container->load('getSecurity_PasswordHasherFactoryService')))));
    }
}
