<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJTZZlzx\App_Shared_Infrastructure_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJTZZlzx/App_Shared_Infrastructure_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJTZZlzx.legacy');

    return;
}

if (!\class_exists(App_Shared_Infrastructure_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJTZZlzx\App_Shared_Infrastructure_KernelDevDebugContainer::class, App_Shared_Infrastructure_KernelDevDebugContainer::class, false);
}

return new \ContainerJTZZlzx\App_Shared_Infrastructure_KernelDevDebugContainer([
    'container.build_hash' => 'JTZZlzx',
    'container.build_id' => '7c91fb72',
    'container.build_time' => 1676995076,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJTZZlzx');
